### ISSUE TITLE
Hello, I encountered the following bug:

### ISSUE THREAD

**Issue by kjyjxy** [rotunba/SSDBM-DSER#1]
when I run NeuMF
 python main.py --method neumf  ---dataset ml-1m --epochs 50 --lr 0.005
I encountered the following bug:TypeError: run() takes exactly 16 arguments (15 given)
How I can run model like NeuMF,, BPR, ITEMPOP?Thank you!

**Comment by rotunba** [comment]
The bug has been fixed. Please try again.

**Comment by kjyjxy** [comment]
It works.Thank you!

**Comment by rotunba** [comment]
Can we close the issue?

**Comment by kjyjxy** [comment]
yes!I just occasionally clicked it .

**Comment by kjyjxy** [comment]
sorry！I did not mean it.

**Comment by rotunba** [comment]
It’s fine. 🙂. Thanks for alerting us about the bug!
